name: Update README

on:
  schedule:
    - cron: "* * */7 * *"
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v4.2.2
      
      - uses: Readme-Workflows/recent-activity@2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
